version: '3.8'

services:
  zookeeper:
    image: zookeeper
    restart: always
  
  kafka:
    image: bitnami/kafka
    restart: always
    platform: linux/amd64
    ports:
      - 9092:9092

    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper